import os

print("""
╦ ╦╔═╗╔╗╔╔═╗  ╦╔╗╔╔═╗╔╦╗╔═╗╦  ╦  ╔═╗╦═╗
╚╦╝║ ║║║║║╣   ║║║║╚═╗ ║ ╠═╣║  ║  ║╣ ╠╦╝
 ╩ ╚═╝╝╚╝╚═╝  ╩╝╚╝╚═╝ ╩ ╩ ╩╩═╝╩═╝╚═╝╩╚═
""")

print("""[1] pip\n[2] pip3\nWhich one do you use?""")
rn = input(">>>")
if rn == '1':
    os.system("pip install speedtest-cli")
    os.system("pip install PySocks")
    os.system("pip install cfscrape")
    os.system("pip install datetime")
    os.system("pip install ssl")
    os.system("pip install threading")
    os.system("pip install imcplib")
    os.system("pip install scapy")
    os.system("pip3 install socks")
    os.system("pip3 install requests")
    os.system("pip3 install socks")
    os.system("pip3 install webdriver_manager")
    os.system("pip3 install websocket")
    os.system("pip3 install websockets")
    os.system("pip3 install selenium")
    os.system("pip3 install nmap")
    os.system("pip3 install undetected_chromedriver")
    os.system("pip3 install cloudscraper")
    os.system("pip3 install impacket")
    os.system("pip3 install psutil")
    os.system("pip3 install yarl")
elif rn == '2':
    os.system("pip install speedtest-cli")
    os.system("pip install PySocks")
    os.system("pip install cfscrape")
    os.system("pip install datetime")
    os.system("pip install ssl")
    os.system("pip install threading")
    os.system("pip install imcplib")
    os.system("pip install scapy")
    os.system("pip3 install socks")
    os.system("pip3 install requests")
    os.system("pip3 install socks")
    os.system("pip3 install webdriver_manager")
    os.system("pip3 install websocket")
    os.system("pip3 install websockets")
    os.system("pip3 install selenium")
    os.system("pip3 install nmap")
    os.system("pip3 install undetected_chromedriver")
    os.system("pip3 install cloudscraper")
    os.system("pip3 install impacket")
    os.system("pip3 install psutil")
    os.system("pip3 install yarl")
else:
    print("?")

os.system("sudo apt-get install nodejs")
os.system("sudo apt-get install npm")
os.system("npm i events")
os.system("npm i fs")
os.system("npm i url")
os.system("npm i net")
os.system("npm i cloudscraper")
os.system("npm i request")
os.system("npm i randomstring")
